server:
  port: 8080
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    password: 2000
    username: postgres
    url: jdbc:postgresql://localhost:5432/teach_spring?currentSchema=jwt_access_refresh
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.PostgreSQL10Dialect

